Warehouse/Warehouse/Controllers/SortedPartsController.cs
using System;

using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataAccess.Entities;
using Warehouse.Models;
using Warehouse.Models.Part;
using Warehouse.Repository;
using System.Collections;
using System.IO;

namespace Warehouse.Controllers
{
    [Authorize]
    public class SortedPartsController : Controller
    {
       // private PartContext db = new PartContext();

        private UnitOfWork<PartContext> unitOfWork = new UnitOfWork<PartContext>();
        private GenericRepository<PartEntity> repository;
        private GenericRepository<CategoryEntity> categoryrepository;
        private GenericRepository<UnitCountEntity> unitcountrepository;
        // private GenericRepository<MOLEntity> molrepository;
        //   private IWarehouseRepository warehouseRepository;
        public SortedPartsController()
        {
            //If you want to use Generic Repository with Unit of work
            repository = new GenericRepository<PartEntity>(unitOfWork);
            categoryrepository = new GenericRepository<CategoryEntity>(unitOfWork);
            unitcountrepository = new GenericRepository<UnitCountEntity>(unitOfWork);
            // molrepository = new GenericRepository<MOLEntity>(unitOfWork);
            //If you want to use Specific Repository with Unit of work
            //   warehouseRepository = new WarehouseRepository(unitOfWork);
        }
        // GET: Parts

        public ActionResult Index()
        {
            return View("SortedPartsList", repository.GetAll().OrderBy(x => x.RusName));
        }
        // GET: Parts/Details/5
        public /*async Task<ActionResult>*/ ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //  PartEntity part = await db.Parts.FindAsync(id);
            var part = repository.GetById(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            if (part.PictureName == null)
            {
                part.PictureName = "NoImage.jpg";
            }
            return View(part);
        }

        public ActionResult CreateRart()
        {
            var countlistfromdb = unitcountrepository.GetAll();
            var categorylistfromdb = categoryrepository.GetAll();
            var model = new PartCreateModel() { UnitCountList = new List<UnitCount>(), PartCategoryList = new List<Models.PartCategories.PartCategory>() };
            foreach (var item in countlistfromdb)
            {
                var unit = new UnitCount() { Id = item.Id.ToString(), UnitCountName = item.UnitCountName };
                model.UnitCountList.Add(unit);
            }
            foreach (var item in categorylistfromdb)
            {
                var cat = new Models.PartCategories.PartCategory()
                {
                    Id = item.Id.ToString(),
                    PartCategoryName = item.Name
                };
                model.PartCategoryList.Add(cat);
            }

            //var countlistfromdb = db.UnitCounts.ToList();
            //var categorylistfromdb = db.PartCategories.ToList();
            //var model = new PartCreateModel() { UnitCountList = new List<UnitCount>(), PartCategoryList = new List<Models.PartCategories.PartCategory>() };
            //foreach (var item in countlistfromdb)
            //{
            //    var unit = new UnitCount() { Id = item.Id.ToString(), UnitCountName = item.UnitCountName };
            //    model.UnitCountList.Add(unit);
            //}
            //foreach (var item in categorylistfromdb)
            //{
            //    var cat = new Models.PartCategories.PartCategory()
            //    {
            //        Id = item.Id.ToString(),
            //        PartCategoryName = item.Name
            //    };
            //    model.PartCategoryList.Add(cat);
            //}
            return View(model);
        }

        // POST: Parts/CreateRart
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateRart(/*[Bind(Include = "RusName,EngName,PartNumber, UnitCountList")]*/ PartCreateModel part)
        {
            if (ModelState.IsValid)
            {
                PartEntity newpart = new PartEntity()
                {
                    Id = Guid.NewGuid(),
                    EngName = part.EngName.Trim(),
                    PartNumber = part.PartNumber.Trim(),
                    RusName = part.RusName.Trim(),
                    UnitCountId = Guid.Parse(part.UnitCountId),
                    LimitQuantity = part.LimitQuantity,
                    CategoryEntityId = Guid.Parse(part.PartCategoryId)
                };
                 repository.Insert(newpart);// with repository
                //with db.context
                // db.Parts.Add(newpart);
                // await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(part);
        }

        //GET: Parts/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var countlistfromdb = unitcountrepository.GetAll();
            var categorylistfromdb = categoryrepository.GetAll();
            var model = new PartEditModel() { UnitCountList = new List<UnitCount>(), Id = id, PartCategoryList = new List<Models.PartCategories.PartCategory>() };
            foreach (var item in countlistfromdb)
            {
                var unit = new UnitCount() { Id = item.Id.ToString(), UnitCountName = item.UnitCountName };
                model.UnitCountList.Add(unit);
            }
            foreach (var item in categorylistfromdb)
            {
                var cat = new Models.PartCategories.PartCategory()
                {
                    Id = item.Id.ToString(),
                    PartCategoryName = item.Name
                };
                model.PartCategoryList.Add(cat);
            }
            var part = repository.GetById(id);
            model.EngName = part.EngName;
            model.PartNumber = part.PartNumber;
            model.RusName = part.RusName;
            model.UnitCount = new UnitCount() { UnitCountName = part.UnitCount.UnitCountName, Id = part.UnitCountId.ToString() };
            model.PartCategory = new Models.PartCategories.PartCategory() { PartCategoryName = part.Category.Name, Id = part.Category.Id.ToString() };
            model.LimitQuantity = part.LimitQuantity;
            return View(model);
        }

        // POST: Parts/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(/*[Bind(Include = "Id,RusName,EngName,PartNumber, UnitCountId, PartCategoryId, LimitQuantity")]*/ PartEditModel part)
        {
            //var editpart = repository.GetById(part.Id);
            //editpart.EngName = part.EngName.Trim();
            //editpart.PartNumber = part.PartNumber.Trim();
            //editpart.RusName = part.RusName.Trim();
            //editpart.UnitCountId = Guid.Parse(part.UnitCountId);
            //editpart.LimitQuantity = part.LimitQuantity;
            //editpart.CategoryEntityId = Guid.Parse(part.PartCategoryId);
            if (ModelState.IsValid)
            {
                var editpart = repository.GetById(part.Id);
                editpart.EngName = part.EngName.Trim();
                editpart.PartNumber = part.PartNumber.Trim();
                editpart.RusName = part.RusName.Trim();
                editpart.UnitCountId = Guid.Parse(part.UnitCountId);
                editpart.LimitQuantity = part.LimitQuantity;
                editpart.CategoryEntityId = Guid.Parse(part.PartCategoryId);

                repository.Update(editpart);
                return RedirectToAction("Index");
            }
                    
            return View(part);
        }

        [Authorize]
        // GET: Parts/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartEntity part = repository.GetById(id); //await db.Parts.FindAsync(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }
        [Authorize]
        // POST: Parts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            // PartEntity part = await db.Parts.FindAsync(id);
            PartEntity part = repository.GetById(id);
            repository.Delete(part);
            // db.Parts.Remove(part);
            //await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public ActionResult GetNameSearch(string rusname)
        {
            var name = rusname.ToLower();
           var names = repository.GetAll().Where(x => x.RusName.ToLower().Contains(name));
            //var names = db.Parts.Where(x => x.RusName.ToLower().Contains(rusname)).ToList();

Warehouse/Warehouse/Views/SortedParts/CreateRart.cshtml
@model Warehouse.Models.PartCreateModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RusName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RusName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RusName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EngName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EngName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EngName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UnitCountList, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.UnitCountId, new SelectList(Model.UnitCountList, "Id", "UnitCountName"), htmlAttributes: new { @class = "form-control" })
            </div>

            @Html.LabelFor(model => model.PartCategoryList, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PartCategoryId, new SelectList(Model.PartCategoryList, "Id", "PartCategoryName"), htmlAttributes: new { @class = "form-control" })
            </div>
            @Html.LabelFor(model => model.LimitQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LimitQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LimitQuantity, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">

                <div class="col-md-offset-2 col-md-10">

                    <button type="submit" class="btn btn-default">Создать</button>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Warehouse/Warehouse/Views/SortedParts/Delete.cshtml
@model DataAccess.Entities.PartEntity

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Part</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EngName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Warehouse/Warehouse/Views/SortedParts/Details.cshtml
@model DataAccess.Entities.PartEntity
@{
    ViewBag.Title = "Details";
}
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RusName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RusName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EngName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EngName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PartNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PartNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UnitCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UnitCount.UnitCountName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LimitQuantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LimitQuantity)
        </dd>
    </dl>
</div>
<div>
    <img src="@Url.Content("~/Content/PartImages/"+ Model.PictureName)" class="img-thumbnail" alt="Cinque Terre" width="800" height="600">
</div>

@using (@Html.BeginForm("Upload", "Parts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <input type="file" name="upload" /><br>
    <input type="submit" value="Загрузить" />
}

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Warehouse/Warehouse/Views/SortedParts/Edit.cshtml
@model Warehouse.Models.Part.PartEditModel

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.RusName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RusName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RusName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EngName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EngName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EngName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PartNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PartNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PartNumber, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.UnitCount.UnitCountName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.UnitCountId, new SelectList(Model.UnitCountList, "Id", "UnitCountName"), @*Model.UnitCount.UnitCountName,*@ htmlAttributes: new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PartCategory.PartCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PartCategoryId, new SelectList(Model.PartCategoryList, "Id", "PartCategoryName"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div> 
        <div class="form-group">
            @Html.LabelFor(model => model.LimitQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LimitQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LimitQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }


    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

Warehouse/Warehouse/Views/SortedParts/SortedPartsList.cshtml
@model IEnumerable<DataAccess.Entities.PartEntity>

@{
    ViewBag.Title = "PartsList";
    // Layout = null;
}

<h2>Перечень запчастей</h2>

<p>
    @if (HttpContext.Current.User.IsInRole("admin"))
    {
        @Html.ActionLink("Добавить новую запчасть", "CreateRart")
    }
</p>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>jQuery UI Autocomplete - Default functionality</title>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @*    <link rel="stylesheet" href="~/Content/Site.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@


    <script>
        $(document).ready(function () { $('#searchrusname').autocomplete({ source: '@Url.Action("GetNameSearchJson")' , minLength: 1, autoFocus: true }); })
        $(document).ready(function () { $('#searchpartnumber').autocomplete({ source: '@Url.Action("GetPartNumberSearchJson")', minLength: 1, autoFocus: true }); })
        //Категории
        $(document).ready(function () { $('#searchcategory').autocomplete({ source: '@Url.Action("GetCategoriesSearchJson")' , minLength: 1, autoFocus: true }); })
    </script>

</head>

<div>
    <div style="float: left;">
        <text> Поиск по наименованию:</text>
        @using (Html.BeginForm("GetNameSearch", "SortedParts", FormMethod.Get, new { enctype = "multipart /form-data" }))
        {
            <div class="ui-widget">
                <input type="text" name="rusname" id="searchrusname">
                <input type="submit" value="Find" />
            </div>
        }
    </div>
    <div style="float: left;">
        @using (Html.BeginForm("GetPartNumberSearch", "SortedParts", FormMethod.Get, new { enctype = "multipart /form-data" }))
        {
            <text> Поиск по артикулу:</text>
            <div class="ui-widget">
                <input type="text" name="partnumber" id="searchpartnumber">
                <input type="submit" value="Find" />
            </div>
        }
    </div>
    <div style="float: left;">
        @using (Html.BeginForm("GetPartOnCategorySearch", "SortedParts", FormMethod.Get, new { enctype = "multipart /form-data" }))
        {
            <text> Поиск по категории:</text>
            <div class="ui-widget">
                <input type="text" name="category" id="searchcategory">
                <input type="submit" value="Find" />
            </div>
        }
    </div>
</div>

    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RusName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartNumber)
            </th>
            <th>

            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RusName)
                    <div>
                        <h6>
                            Лим. на складе:
                            @Html.DisplayFor(modelItem => item.LimitQuantity)
                            @Html.DisplayFor(modelItem => item.UnitCount.UnitCountName)
                        </h6>
                      <p>
                          <button style="background-color: #4CAF50;   border: none;

  color: white;
  padding: 2px 5px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 12px;" onclick="
                        navigator.clipboard.writeText('@(item.RusName)     @(item.PartNumber)    @(item.UnitCount.UnitCountName)')
                        "; allow="clipboard-read; clipboard-write">
    Скопировать в буффер</button>
                          </p>  
                    </div>  
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PartNumber)
                </td>
                <td>
                    @if (item.PictureName == null)
                    {
                        <img src="@Url.Content("~/content/PartImages/noimage.jpg")" height="150">
                    }
                    else
                    {
                        <img src="@Url.Content("~/content/PartImages/"+ item.PictureName)"  height="150">
                    }
                   
                </td>

                <td width="200">
                    @if (HttpContext.Current.User.IsInRole("admin"))
                    {
                    <p>
                        @Html.ActionLink("Изменить", "Edit", new { id = item.Id })
                    </p>
                    <p>
                        @Html.ActionLink("Подробности", "Details", new { id = item.Id }, new { id = item.Id })
                    </p>
                    <p>
                        @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
                    </p>
                    }
                    <h6>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </h6>
                </td>
            </tr>
        }
    </table>