Warehouse/Warehouse/Models/Bill/CreateBillModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Warehouse.Models
{
    public class CreateBillModel
    {
        public CreateBillModel()
        {
            TimeOfCreate = DateTime.Now;
        }
        [Display(Name = "Заказчик")]
        public string CustomerName { get; set; }
        [Display(Name = "Дата")]
       [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime TimeOfCreate { get; set; }

    }
}

Warehouse/Warehouse/Models/Bill/DeleteBillModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Warehouse.Models
{
    public class DeleteBillModel
    {
        [Display(Name = "Заказчик")]
        public string CustomerName { get; set; }
        [Display(Name = "Дата")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime TimeOfCreate { get; set; }
    }
}

Warehouse/Warehouse/Models/Bill/EditBillModel.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Warehouse.Models.Order;

namespace Warehouse.Models
{
    public class EditBillModel
    {
        //[Display(Name = "Наименование")]
        //public string PartName { get; set; }
        //[Display(Name = "Артикул")]
        //public string PartNumber { get; set; }
        //[Display(Name = "Количество")]
        //public int Count { get; set; }
        public Guid BillId { get; set; }
        public string BillName { get; set; }
      //  public IEnumerable<PartItem> PartItems { get; set; }
        public ICollection<BillItem> BillItems { get; set; }
        public PartItem NewPartItem { get; set; }
    }
}

Warehouse/Warehouse/Controllers/CustomerController.cs
using Aspose.Cells;
using DataAccess;
using DataAccess.Entities;
using Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace Warehouse.Controllers
{
    public class CustomerController : Controller
    {
        private PartContext db = new PartContext();
    

        // GET: Custome
        public CustomerController()
        {

        }

        public async Task<ActionResult> Index()
        {
                      
            var customers = await db.Customers.OrderBy(x => x.CustomerName).ToListAsync();
            var custlist = new List<Customer>();
            foreach (var item in customers)
            {
                custlist.Add(new Customer() { Id = item.Id, CustomerName = item.CustomerName });
            }
           
            return View(custlist);
        }



        // GET: Custome/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Custome/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Custome/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CustomerName")]Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    customer.Id = Guid.NewGuid();

                    var cust = new CustomerEntity() {
                     Id = customer.Id, CustomerName = customer.CustomerName};
                    
                    db.Customers.Add(cust);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }

            }
            catch
            {
                return View();
            }
          
        }



        // GET: Custome/Edit/5
        public ActionResult Edit(Guid id)
        {
            var cust = db.Customers.Where(x => x.Id == id).FirstOrDefault();
            var editcust = new Customer() { Id = id, CustomerName = cust.CustomerName };
            return View(editcust);
        }

        // POST: Custome/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Guid id, [Bind(Include = "CustomerName")]Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var cust = new CustomerEntity() { Id = id, CustomerName = customer.CustomerName };
                    db.Entry(cust).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
           
            }
            catch
            {
                return View();
            }
        }

        // GET: Custome/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Custome/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult GetCustomerSearchJson(string term)
        {
            var customer = term.ToLower();
            var customers = db.Customers.Where(x => x.CustomerName.ToLower().Contains(term)).Select(x => x.CustomerName).Take(10).ToList();
            return Json(customers, JsonRequestBehavior.AllowGet);
        }

    }
}

Warehouse/Warehouse/Controllers/PartsController.cs
using System;

using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataAccess.Entities;
using Warehouse.Models;
using Warehouse.Models.Part;

namespace Warehouse.Controllers
{
    [Authorize]
    public class PartsController : Controller
    {
        private PartContext db = new PartContext();

        // GET: Parts

        public async Task<ActionResult> Index()
        {

            return View("PartsList", await db.Parts.OrderBy(x => x.RusName).ToListAsync());
        }

        //public async Task<ActionResult> PictureRename()
        //{
        //    var parts = db.Parts.ToList();
        //    foreach (var item in parts)
        //    {
        //        if (item.PictureName == null)
        //        {
        //            parts.Remove(item);
        //        }
        //    }


        //    return View("PartsList", await db.Parts.OrderBy(x => x.RusName).ToListAsync());
        //}


        // GET: Parts/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartEntity part = await db.Parts.FindAsync(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            if (part.PictureName == null)
            {
                part.PictureName = "NoImage.jpg";
            }
            return View(part);
        }


        public ActionResult CreateRart()
        {
            var countlistfromdb = db.UnitCounts.ToList();
            var categorylistfromdb = db.PartCategories.ToList();

            var model = new PartCreateModel() { UnitCountList = new List<UnitCount>(), PartCategoryList = new List<Models.PartCategories.PartCategory>() };
            foreach (var item in countlistfromdb)
            {
                var unit = new UnitCount() { Id = item.Id.ToString(), UnitCountName = item.UnitCountName };
                model.UnitCountList.Add(unit);
            }
            //
            foreach (var item in categorylistfromdb)
            {
                var cat = new Models.PartCategories.PartCategory()
                {
                    Id = item.Id.ToString(),
                    PartCategoryName = item.Name
                };
                model.PartCategoryList.Add(cat);
            }
            //
            return View(model);
        }

        // POST: Parts/CreateRart
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateRart(/*[Bind(Include = "RusName,EngName,PartNumber, UnitCountList")]*/ PartCreateModel part)
        {
            if (ModelState.IsValid)
            {
                PartEntity newpart = new PartEntity()
                {
                    Id = Guid.NewGuid(),
                    EngName = part.EngName.Trim(),
                    PartNumber = part.PartNumber.Trim(),
                    RusName = part.RusName.Trim(),
                    UnitCountId = Guid.Parse(part.UnitCountId),
                    LimitQuantity = part.LimitQuantity,
                    CategoryEntityId = Guid.Parse(part.PartCategoryId)

                };
                db.Parts.Add(newpart);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(part);
        }

        //GET: Parts/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var countlistfromdb = await db.UnitCounts.ToListAsync();
            var categorylistfromdb = db.PartCategories.ToList();

            var model = new PartEditModel() { UnitCountList = new List<UnitCount>(), Id = id, PartCategoryList = new List<Models.PartCategories.PartCategory>() };
            foreach (var item in countlistfromdb)
            {
                var unit = new UnitCount() { Id = item.Id.ToString(), UnitCountName = item.UnitCountName };
                model.UnitCountList.Add(unit);
            }
            //
            foreach (var item in categorylistfromdb)
            {
                var cat = new Models.PartCategories.PartCategory()
                {
                    Id = item.Id.ToString(),
                    PartCategoryName = item.Name
                };
                model.PartCategoryList.Add(cat);
            }

            var part = await db.Parts.FindAsync(id);
            model.EngName = part.EngName;
            model.PartNumber = part.PartNumber;
            model.RusName = part.RusName;
            model.UnitCount = new UnitCount() { UnitCountName = part.UnitCount.UnitCountName, Id = part.UnitCountId.ToString() };
            model.PartCategory = new Models.PartCategories.PartCategory() { PartCategoryName = part.Category.Name, Id = part.Category.Id.ToString() };
            model.LimitQuantity = part.LimitQuantity;
            return View(model);
        }

        // POST: Parts/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(/*[Bind(Include = "Id,RusName,EngName,PartNumber, UnitCountId, PartCategoryId, LimitQuantity")]*/ PartEditModel part)
        {
            var editpart = db.Parts.Find(part.Id);
            editpart.EngName = part.EngName.Trim();
            editpart.PartNumber = part.PartNumber.Trim();
            editpart.RusName = part.RusName.Trim();
            editpart.UnitCountId = Guid.Parse(part.UnitCountId);
            editpart.LimitQuantity = part.LimitQuantity;
            editpart.CategoryEntityId = Guid.Parse(part.PartCategoryId);
            if (ModelState.IsValid)
            {
                db.Entry(editpart).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(part);
        }


        [Authorize]
        // GET: Parts/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartEntity part = await db.Parts.FindAsync(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }
        [Authorize]
        // POST: Parts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            PartEntity part = await db.Parts.FindAsync(id);
            db.Parts.Remove(part);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public ActionResult GetNameSearch(string rusname)
        {
            var name = rusname.ToLower();
            var names = db.Parts.Where(x => x.RusName.ToLower().Contains(rusname)).ToList();

            // return Json(names, JsonRequestBehavior.AllowGet);
            return View("PartsList", names);
        }



        public ActionResult NameToNumberConvert(string term)
        {
            var name = term.ToLower();
            var numbers = db.Parts.Where(x => x.RusName == term.ToLower()).Select(x => x.PartNumber).Take(10).ToList();
            return Json(numbers, JsonRequestBehavior.AllowGet);
        }

        public ActionResult NumberToNameConvert(string term)
        {
            var name = term.ToLower();
            var numbers = db.Parts.Where(x => x.PartNumber == term.ToLower()).Select(x => x.RusName).Take(10).ToList();
            return Json(numbers, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetNameSearchJson(string term)
        {
            var name = term.ToLower();
            var names = db.Parts.Where(x => x.RusName.ToLower().Contains(term)).Select(x => x.RusName).Take(10).ToList();
            return Json(names, JsonRequestBehavior.AllowGet);
        }



        public ActionResult GetPartNumberSearch(string partnumber)
        {
            var name = partnumber.ToLower();
            var names = db.Parts.Where(x => x.PartNumber.ToLower().Contains(partnumber)).ToList();

            // return Json(names, JsonRequestBehavior.AllowGet);
            return View("PartsList", names);
        }

        public ActionResult GetPartNumberSearchJson(string term)
        {
            var number = term.ToLower();
            var numbers = db.Parts.Where(x => x.PartNumber.ToLower().Contains(term)).Select(x => x.PartNumber).Take(10).ToList();

            // return Json(names, JsonRequestBehavior.AllowGet);
            return Json(numbers, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EngNameToPartConvert(string term)
        {

            var name = term.ToLower();
            var part = db.Parts.Where(x => x.EngName == term.ToLower()).Select(x => new { x.RusName, x.PartNumber }).Take(10).ToList();
            return Json(part, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ContentResult Upload(HttpPostedFileBase upload, PartEntity pe)
        {
            if (upload != null)
            {

Warehouse/Warehouse/Views/Bill/Create.cshtml
@model Warehouse.Models.CreateBillModel
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>jQuery UI Autocomplete - Default functionality</title>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @*    <link rel="stylesheet" href="~/Content/Site.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@

    <script>

        $(document).ready(function () { $('#customer').autocomplete({ source: '@Url.Action("GetCustomerSearchJson", "Customer")' , minLength: 1, autoFocus: true }); })
       
    </script>

</head>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateBillModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control", id = "customer" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeOfCreate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOfCreate, new { htmlAttributes = new { @class = "form-control", @value = Model.TimeOfCreate} })
                @Html.ValidationMessageFor(model => model.TimeOfCreate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Warehouse/Warehouse/Views/Bill/CreateBillItem.cshtml
@model Models.BillItem

<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script>

        $(document).ready(function () { $('#searchrusname').autocomplete({ source: '@Url.Action("GetNameSearchJson","Parts")' , minLength: 1, autoFocus: true }); })
        $(document).ready(function () { $('#searchpartnumber').autocomplete({ source: '@Url.Action("GetPartNumberSearchJson", "Parts")' , minLength: 1, autoFocus: true }); })

        $(document).ready(function () {
            $('#submitPartNumber').click(function (e) {
            e.preventDefault();
                var name = $('#searchpartnumber').val();
                name = encodeURIComponent(name);
             
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("NumberToNameConvert", "Parts")",
                    data: { term: name },
                    dataType: "json", 
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        if (name != '') {
                            $('#searchrusname').val(data[0]);
                        }
                    },
                    error: function () {
                        alert("Error occured!!")
                    }
                });  

            });
            $('#submitPartName').click(function (e) {
            e.preventDefault();
                var name = $('#searchrusname').val();
                //name = encodeURIComponent(name);
             
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("NameToNumberConvert", "Parts")",
                    data: { term: name },
                    dataType: "json", 
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        $('#searchpartnumber').val(data[0]);
                    },
                    error: function () {
                        alert("Error occured!!")
                    }
                });  
            });
    });

    </script>
</head>



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Добавление запчасти:</h4>
        <hr />
        
       
        <div class="form-inline">
            @Html.LabelFor(model => model.PartName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartName, new { htmlAttributes = new { @class = "form-control", @id = "searchrusname" } })
                <input type='button' id="submitPartName" value='Проверить по наименованию' />
                @Html.ValidationMessageFor(model => model.PartName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-inline">
            @Html.LabelFor(model => model.PartNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartNumber, new { htmlAttributes = new { @class = "form-control", @id = "searchpartnumber" } })
                <input type='button' id="submitPartNumber" value='Проверить по артикулу' />
                @Html.ValidationMessageFor(model => model.PartNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-inline">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Warehouse/Warehouse/Views/Bill/Delete.cshtml
@model Warehouse.Models.DeleteBillModel

<h3>Are you sure you want to delete this?</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeOfCreate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeOfCreate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Warehouse/Warehouse/Views/Bill/Details.cshtml
@model IEnumerable<Models.BillItem>

@*<p>
    @Html.ActionLink("Create New", "CreateBillItem", new {id = Model.First().BillId })
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PartName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PartNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PartName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PartNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Warehouse/Warehouse/Views/Bill/EditBill.cshtml
@model Warehouse.Models.EditBillModel

@{
    //ViewBag.Title = "EditOrder";
    int i = 1;
}

<h2>Название счета:  @Model.BillName</h2>
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script>
         $(document).ready(function () { $('#searchrusname').autocomplete({ source: '@Url.Action("GetNameSearchJson","Parts")' , minLength: 1, autoFocus: true }); })
         $(document).ready(function () { $('#searchpartnumber').autocomplete({ source: '@Url.Action("GetPartNumberSearchJson", "Parts")' , minLength: 1, autoFocus: true }); })

        $(document).ready(function () {
            $('#submitengmame').click(function (e) {
            e.preventDefault();
                var name = $('#engpartname').val();
               // name = encodeURIComponent(name);

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("EngNameToPartConvert", "Parts")",
                    data: { term: name },
                    dataType: "json",
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        if ($('#engpartname').val() != '') {
                            $('#searchrusname').val(data[0].RusName);
                            $('#searchpartnumber').val(data[0].PartNumber);
                        }
                    },
                    error: function () {
                        alert("Error occured!!")
                    }
                });

            });

            $('#submitPartNumber').click(function (e) {
            e.preventDefault();
                var name = $('#searchpartnumber').val();
             //   name = encodeURIComponent(name);

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("NumberToNameConvert", "Parts")",
                    data: { term: name },
                    dataType: "json",
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        if ($('#searchpartnumber').val() != '') {
                            $('#searchrusname').val(data[0]);
                        }
                    },
                    error: function () {
                        alert("Error occured!!")
                    }
                });

            });
            $('#submitPartName').click(function (e) {
            e.preventDefault();
                var name = $('#searchrusname').val();
                //name = encodeURIComponent(name);

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("NameToNumberConvert", "Parts")",
                    data: { term: name },
                    dataType: "json",
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        $('#searchpartnumber').val(data[0]);
                    },
                    error: function () {
                        alert("Error occured!!")
                    }
                });
            });
    });

    </script>
</head>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("№")
            </th>
            <th>
                @Html.DisplayName("Наименование:")
            </th>
            <th>
                @Html.DisplayName("Артикул:")
            </th>
            
            <th>
                @Html.DisplayName("Количество:")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BillItems)
        {

            <tr>
                <td>
                    @i.ToString()
                    @{
                        i++;
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PartName)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.PartNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Count)
                </td>

            </tr>
        }
    </tbody>

</table>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(m => m.BillItems)
        <div class="form-inline">
            @Html.LabelFor(model => Model.NewPartItem.PartRusName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => Model.NewPartItem.PartRusName, new { htmlAttributes = new { @class = "form-control", id = "searchrusname" } })
                <input type='button' id="submitPartName" value='Проверить по наименованию' />
                @Html.ValidationMessageFor(model => model.NewPartItem.PartRusName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-inline">
            @Html.LabelFor(model => Model.NewPartItem.PartEngName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => Model.NewPartItem.PartEngName, new { htmlAttributes = new { @class = "form-control", id = "engpartname" } })
                <input type='button' id="submitengmame" value='Проверить по англ названию' />
                @Html.ValidationMessageFor(model => model.NewPartItem.PartEngName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-inline">
            @Html.LabelFor(model => Model.NewPartItem.PartNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => Model.NewPartItem.PartNumber, new { htmlAttributes = new { @class = "form-control", id = "searchpartnumber" } })
                <input type='button' id="submitPartNumber" value='Проверить по артикулу' />
                @Html.ValidationMessageFor(model => model.NewPartItem.PartNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => Model.NewPartItem.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => Model.NewPartItem.Count, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.NewPartItem.Count, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-inline">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}